app/views/_authors.scala.html, app/views/item.scala.html, app/views/item_browse.scala.html, app/views/topic.scala.html
The first 10 authors are shown and `et al` added if there are more than 10.
For the Item view only, a total count of authors is displayed and the
ability to hide/show them is included.
Fixes #7
=> Hides excess authors

app/views/item/show.scala.html
closes #25 
This is the onlycode necessary to display the abstract along with the item. Everything else is done in configuration.
I'll paste in my updated `/cmodel` dump in a comment which includes the additional finders and mappings, etc.
=> Display abstract for an item

app/controllers/Application.scala, app/workers/Harvester.scala, conf/routes
Invoked via a URL parameter to /knip: force=true (defaults to false) with behavior that if force is false,
an attempt to add an item that already exists with given obj_key will fail, whereas if force is true, current
item will be deleted and a new item with same obj_key created.
fixes #26
fixes #28
=> Adds 'force' mode for knip (Known Item Pull)

app/views/content_format/index.scala.html, app/views/content_type/index.scala.html, app/views/layout/main.scala.html, app/views/publisher/index.scala.html, app/views/resource_map/index.scala.html, app/views/scheme/index.scala.html, app/views/static/home.scala.html, app/views/static/workbench.scala.html, app/views/utils/cmodel_create.scala.html, public/stylesheets/main.css
closes #17 
Updates all sidenavs to use list-group
The size of the sidenav div had to grow for some of these to work
properly without the badge looking weird (dropping to it’s own line and
overlapping). If we are concerned with that, I can spend some more time
on that now or we can just address it later if/when it becomes a real
estate problem. My current thought is to leave it like this and move to
a truly fluid layout eventually that’ll minimize this “problem”. I’ll
open a ticket to do that and if we decide not to we can close it. (Opened as #32)
=> 17 sidenav

app/controllers/Search.scala, app/views/layout/main.scala.html, app/views/search/index.scala.html, app/views/search/item_results.scala.html, app/views/search/searchform.scala.html, app/views/search/topic_results.scala.html, app/views/tags/pagination.scala.html, app/views/tags/summary.scala.html, conf/routes
closes #40
You'll notice I've created an additional controller solely for Search related pages. I like it this way, but I can move this work back to `controllers/Application.scala` if it's preferred for this project. If we do both like it, I'll open a ticket to move move most of `controllers/Application.scala` into smaller purpose focused controllers (likely along `route` lines like the `views` folders hierarchy).
Also worth noting is that I didn't use the Play form helper. I found it clunky for this non-model backed form (I did have it in there for a while but to get the layout I wanted this was saner). #23 may want to consider just ditching the helpers as well, although for model backed forms it may make sense to stick with helpers and write a custom renderer... I'll leave further …
=> Initial Item and Topic Search UI

app/models/Item.scala, app/workers/Cataloger.scala
@JPrevost Could you have a look and comment? The bug report was for multiple item appearances under a topic - but I think the cause is the other side of the equation: when a finder obtains multiple occurrences of the same value, it blindly adds a link for each. For the typical case (say cardinality n for authors) each value will be distinct, but in your case they were the same. Fix just checks for existence of a topic-item link, and skips the add. Thanks
=> Prevents multiple assignment of same topic to an item. Fixes #74

app/controllers/Application.scala, app/models/Item.scala, app/views/item/show.scala.html, conf/routes
There are a few METS field id values that seem arbitrary so they are
left out (they are incremental div id numbers that are not referenced
elsewhere for example).
File names are their own method, so the Packager should be able to use
the same method to generate a name matching the `Item#toMets` method. (And
thus if we need to make a change, we should be able to just change what
that method does without too much concern.
`toMets` should be fairly forgiving and just generate a file with
whatever metadata exists for an Item that we’ve mapped to METS. As
such, the notion of a ContentProfile is not actually being checked for
this work. I’m fine with adding it back in if we decide an Analyst
really will want the flexibility to Catalog metadata without including
it in the mets.xml file.
The …
=> METS generator

conf/application.conf
As a first round of work on #22, this provides default db url and a
fake email api key.
If they are defined in the ENV, the ENV values win, so Heroku and
Travis should remain fine with this config but this has the benefit of
not requiring setting those values if they are the development versions
like we already do for elasticsearch. If a developer or deployed server
desires non-default values, they can easily set via ENV.
=> Default DB URL and Fake Email Key

app/controllers/Application.scala, app/controllers/ItemController.scala, app/views/collection/index.scala.html, app/views/hold/browse.scala.html, app/views/item/browse.scala.html, app/views/item/show.scala.html, app/views/publisher/edit.scala.html, app/views/publisher/show.scala.html, app/views/search/item_results.scala.html, app/views/topic/show.scala.html, conf/routes
Moves Item related features to own Controller as I created routes for
viewing mets, downloading package and sending package which will be
quite useful for this stage of development even if they are removed
later (or only available to analyst or whatever).
This should be moved to a worker as it is a blocking request in this sample. There is no error state handling or even redirection back to a sane location. It just blindly claims it may have worked.
work on #83 (but maybe not close that ticket until this is moved Async)
=> First draft of an Actual Deposit

app/controllers/Search.scala, app/views/search/item_results.scala.html, app/views/search/topic_results.scala.html, public/stylesheets/main.css
This also includes some updated styling on both Topic and Item search
result pages.
closes #107 
This is just one way of how to distinguish between subscribed and non-subscribed Topics in search results.
=> Displays Subscription Status on Topic Results

app/models/Topic.scala, app/views/topic/show.scala.html, test/unit/TopicSpec.scala
=> Adds delivery count badge to Subscribe button on topic page

app/controllers/Application.scala, app/views/static/sandbox.scala.html, app/views/static/workbench.scala.html, app/workers/Cataloger.scala, conf/routes
=> Adds an XPath expression testing UI

app/models/ContentProfile.scala, app/models/ResourceMap.scala, test/unit/ResourceMapSpec.scala
Also reverts change in ContentProfile (insert -> update) method, which should only be used for Long DB
keys, according to Play documentation.
Fixes #137
=> Allows SWORD Url to be optional

app/models/Subscriber.scala, app/views/topic/show.scala.html
by subtracting any items already transferred
Closes #124
=> Improves calculation for new subscription delivery count

app/controllers/Application.scala, app/models/Agent.scala, app/models/Subscriber.scala, app/models/TopicPick.scala, app/views/subscriber/dashboard.scala.html, app/views/topic/show.scala.html, app/views/topic_pick/browse.scala.html, app/workers/Conveyor.scala, conf/evolutions/default/6.sql, conf/routes, test/unit/AgentSpec.scala, test/unit/SubscriberSpec.scala, test/unit/TopicPickSpec.scala
=> Adds topic selections for subscribers

app/controllers/Application.scala, app/controllers/AuthenticationController.scala, app/views/collection/create.scala.html, app/views/finder/create.scala.html, app/views/harvest/create.scala.html, app/views/scheme/create.scala.html, app/views/validator/create.scala.html, test/ApplicationSpec.scala, test/integration/AuthenticationPagesSpec.scala, test/integration/CollectionPagesSpec.scala, test/integration/DashboardPagesSpec.scala, test/integration/FinderPagesSpec.scala, test/integration/HarvestPagesSpec.scala, test/integration/IntegrationSpec.scala, test/integration/PublisherPagesSpec.scala, test/integration/SchemePagesSpec.scala, test/integration/ValidatorPagesSpec.scala
https://github.com/MITLibraries/scoap3hub/compare/128_roles?expand=1#diff-d329b37da40ee3da83671939b016c05fR41 allows Integration Tests for non-authenticated users to run with tests that logically require existing users by have the current test user use a specific Identity value instead of Id = 1.
Primarily harvest page specs, but also includes Publisher Page Specs that were not possible until the above Test ENV user logic change was made.
=> Harvest Pages Roles

.travis.yml, build.sbt, project/build.properties, project/plugins.sbt
This will likely not work, but what the heck.
Updates sbt, scala, jdbc (not oracle even if my commit not mentions that... it's still posgresql), play and re-enables coverage.
=> 162 ci crashes

app/controllers/Application.scala, test/integration/HoldPagesSpec.scala, test/integration/TopicPickPagesSpec.scala
part of #128
See #170 for why some tests are pending. In short, the controller
methods call an actor which is not available in our current test
environment. It’s solve-able, but non-trivial. The controllers are
indeed protected by the appropriate roles/subscriber affiliation but
we’re not really confirming that a hold is resolved properly (or not)
as it always seems to not be resolved due to the lack of the worker.
=> Hold Pages Spec and Topic Pick Pages Spec

.travis.yml
This will hopefully allow us to leave fork in Test on while still getting stable Travis builds. There is a ticket referenced in the commit that will hopefully get resolved so we can switch back eventually (this may also not really fix anything. We'll see over time).
=> Switch to old Travis infrastructure

.sbtopts, .travis.yml, build.sbt
Switching back to the new Travis platform with `sudo: false`.
Fork in Test:
I believe I am avoiding the issues I ran into locally without forking
for tests by increasing MaxMetaspaceSize. For now, I have includes settings
in project root .sbtopts that work for me. I can remove that from the repo
and only use that locally if it seems others may want different settings.
Also:
— cache ivy2/cache for faster builds on Travis!
— sets -J-XX:ReservedCodeCacheSize=256M but I don't think this mattered (or hurts though).
=> Test new travis platform again

app/controllers/ItemController.scala, app/models/HubUtils.scala, app/models/Item.scala, app/views/item/notopics.scala.html, app/views/static/workbench.scala.html, app/workers/Harvester.scala, conf/routes, test/integration/ItemPagesSpec.scala, test/integration/WorkbenchPagesSpec.scala, test/unit/ItemSpec.scala
Items with no Topics is a sign of an error state in the Cataloger as it
should always assign either Any or None topics.
This should help us identify Items where the Cataloging failed and thus
determine what next steps to take.
Closes #69
=> Method to expose Items with no Topics

app/models/Harvest.scala, app/models/HubUtils.scala, app/models/User.scala, app/views/email/abort_harvest.scala.txt, app/workers/Harvester.scala, test/unit/UserSpec.scala
Any lack of response or non-200 response code will revert the harvest.
All users with the role `sysadmin` will receive an email with details.
Test Harvest services URLs to throw different conditions:
1) http://repo.scoap3.org/oai2d (200 case, only condition where harvest continues)
2) http://repo.mit.edu/oai2d timesout (rescue: java.net.ConnectException)
3) http://localhost:9000/oai2d (404: default case)
4) http://localhost:9900/oai2d (rescue: java.net.ConnectException)
5) http://asdffdsaasdf.com/oai2d (rescue: java.net.ConnectException)
- Also fixes a bug in `User#hasRole(role)` where all users were treated as
having a role as long as any user had the role.
- This work is part of #211. There is one condition left in that ticket before
we close it. Namely, checking for OAI errors during …
=> Handle exceptions during initial harvest start

app/workers/Harvester.scala
This is starting to get a bit messy, but I think this ends the work in this general area so maybe it's okay.
closes #214
=> Handle non-oai response during Harvest

app/views/search/topic_results.scala.html, test/views/SearchViewsSpec.scala
This also adds View testing for both Search Result Templates which is a
fairly easy way to test the Views without worrying about the external
elasticsearch dependency.
closes #216
=> Topic results handle optional Subscriber

app/models/Subscriber.scala
=> Removes join table row to fix foreign key violation on interest deletion

app/models/Subscriber.scala
closes #223
Based on the play24 branch so needs to be added after #224 is merged
=> Resolves deprecation warning

app/models/Transfer.scala, app/views/email/sword_transfer_failure.scala.txt, app/workers/Conveyor.scala, test/unit/TransferSpec.scala
This handles both non-responses and non-success responses when
attempting a Sword transfer.
closes #114
=> Read response of attempted Sword

app/controllers/Application.scala, app/models/Collection.scala, app/views/collection/create.scala.html, app/views/email/unhandled_collections.scala.txt, app/workers/Cataloger.scala, app/workers/Harvester.scala, app/workers/Indexer.scala, conf/evolutions/default/11.sql, test/unit/CollectionSpec.scala
If any Collections are detected in an OAI Harvest that are not handled,
an email is sent to sysadmins (this may want to change eventually to
instead email the appropriate Analysts but for now sysadmins works well
for us).
This also adds a feature to create Inactive Collections which is
essentially stating you have no interest in the Collection which will
prevent notification when it is detected again on a future Harvest.
closes #81
=> Detects unhanded collections in OAI feed

app/controllers/Application.scala, app/services/email.scala, app/workers/Harvester.scala
Uses mailinator.com for disposable email. Every real address foo@bar.com becomes fooatbar.com@mailinator.com
which can be examined via web UI (and API)
Closes #235
=> Adds disposable target for testing email function

app/controllers/Application.scala, app/models/Plan.scala, app/models/Subscriber.scala, app/views/layout/main.scala.html, app/views/static/home.scala.html, app/views/subscriber/dashboard.scala.html, app/views/subscription/browse.scala.html, conf/routes, test/integration/NavigationPagesSpec.scala, test/unit/PlanSpec.scala, test/unit/SubscriberSpec.scala
A Drag-and-Drop interface added to dashboard, making it easy and intuitive to assign schemes (and thus all
the subscriptions based on their topics) to plans. DND also added for assigning channels to plans.
Closes #226
=> Improves plan visibility and control in dashboard

app/models/Subscription.scala, test/unit/SubscriptionSpec.scala
=> Adds active status to finding subscriptions for a subscriber

app/controllers/Application.scala, app/models/Harvest.scala, app/views/harvest/create.scala.html, conf/application.conf, conf/routes, test/integration/HarvestPagesSpec.scala, test/unit/HarvestSpec.scala
The intent of this route and method are for a cron-like job to kick off
the process. As such, we need to handle this in a non-logged in state.
The application defined key should suffice for our level of protection
needs.
Other changes include: all Harvests default to frequency of 1 and that
cannot be changed in the UI. Admins can still kick off a harvest with a
greater frequency for catchup or testing purposes in the manual harvest
start form.
closes #206
=> Method to kick off all harvests (protected by application key)

app/workers/Cataloger.scala
This is a start towards catching exceptions in the Cataloger.
Determining what we want to do seems important here.
Thoughts on how to proceed are welcome. Mine are mostly that it would be good to catch more specific Exceptions when possible and fallback on the generic Exception only as a last resort... but as I'm not sure if we'll handle the different exceptions differently, I'm not sure if that makes it clearer or muddier.
see #211
=> Detects and does very little with Cataloger Errors

app/controllers/ItemController.scala, app/models/Item.scala, app/models/Publisher.scala, app/views/item/notopics.scala.html, app/views/static/workbench.scala.html, conf/routes, test/integration/ItemPagesSpec.scala, test/unit/ItemSpec.scala, test/unit/PublisherSpec.scala
- adds a method to explictily check for `Any/None` topics and uses that in determing problem Items
- adds a PullKnownItem link on the Items missing Topics page to allow sysadmins to attempt
a reharvest
- note: this does not allow reharvesting from Publishers with multiple Harvests at this time
- allows sysadmins to delete an Item entirely from the Items missing Topics page if they determine
that is an appropriate course of action for the Item (i.e. they happen to know it is not
relevant to hub Subscribers or it was retracted upstream or something).
closes #255
=> Reharvestable Items from Items missing Topics page

app/controllers/Application.scala
This prevents batch harvests from requesting a date that is older than
yesterday with the assumption that it’s safest to not request an OAI
feed for today as more data may be added later we’d miss. I’m not
entirely sure that’s valid logic, but this seems safe. The harvester
increments the updated date hence the need to make sure it is less than
yesterday (i.e. updated needs to be two days ago to actually run which
would then get incremented by 1 to be a harvest for yesterday… clear as
mud?).
Admin kicked off harvests and knips are not limited by date. Only the
batch starter.
closes #240
=> Prevent batch harvests from requesting invalid dates

app/views/subscriber/dashboard.scala.html, public/stylesheets/main.css
This could get fancier by not highlighting the Plan the Scheme is currently in as a valid drop target, but this is nice and simple and addresses the biggest UX concern.
closes #242
=> Highlights valid drop targets on Subscriber Dashboard

app/controllers/Application.scala, app/models/Subscriber.scala, app/views/layout/main.scala.html, app/views/subscriber/dashboard.scala.html, conf/routes, test/unit/SubscriberSpec.scala
This is admittedly a bit hacky, but it should be adequate for our needs.
I felt keeping state in the DB for this, but not for things like Item
status (cataloging state essentially) seemed a bit odd.
closes #113
=> Allow Subscriber#holds and #holdCount to exclude an Item

app/workers/Conveyor.scala
If a Subscriber had multiple Agents that matched a Topic, it was
possible for the Conveyor to attempt to Subscribe or Recommend the same
Topic multiple times.
This prevents that from happening.
Closes #294
Closes #296
=> Prevent Conveyor from Subscribing or Recommending duplicates

README.md, app/controllers/AuthenticationController.scala, app/services/OAuth2.scala, app/views/login/index.scala.html, conf/application.conf, conf/authentication.conf, test/ApplicationSpec.scala, test/integration/AuthenticationPagesSpec.scala, test/integration/CullPagesSpec.scala, test/integration/DashboardPagesSpec.scala, test/integration/HarvestPagesSpec.scala, test/integration/PublisherPagesSpec.scala, test/integration/SubscriberUserPagesSpec.scala, test/integration/UserDashboardPagesSpec.scala
This provides support for Google and MIT OAuth, and thus likely others.
closes #292
=> Allow multiple OAuth providers to be used

app/controllers/Application.scala, app/controllers/Search.scala, app/models/Validator.scala, app/services/jsonModel.scala, app/workers/Cataloger.scala, app/workers/Conveyor.scala, app/workers/Harvester.scala, app/workers/Indexer.scala, app/workers/Packager.scala, app/workers/Reaper.scala, conf/logback.xml
Removes file based log and just uses stdout which is appropriate for
our use on Heroku, local dev and in CI.
Closes #222
Also makes the switch from println to Loggers.
All code that was actively bring println’ed has a level of Info or
Higher (i.e. Info, Warn, Error as seemed appropriate).
Commented out println statements were changed to Logger.debug with the
comments removed so they’ll show up if you change your log level
without having to uncomment/recomment a bunch of code.
A nice side effect of this work is that it should allow our external
log drains to be more useful.
=> Use Loggers

app/views/hold/browse.scala.html, public/stylesheets/main.css
=> Adds matched topic information to hold in browse list

app/views/item/show.scala.html
closes #327
This adds links everything in the `accessUri` metadata fields.
I considered removing the XML link or prioritizing a single download (like PDFa if it exists, the pdf, then XML but wasn't sure that was needed. I'm happy to add that in if we think it's useful to have a single download link even when upstream they have 2 or 3).
=> Adds download links to all known full text

conf/routes, public/robots.txt
closes #333 
This seems like it should work for a while for us (or at least until we have a better plan).
=> Adds robots.txt

conf/evolutions/default/14.sql, conf/routes
This adds some likely useful indexes. There are other candidate fields to index, but as each requires some level of overhead this seemed like a good start.
The second commit reorders the robots.txt related route as the compiler was complaining about it the other way.
=> 332 db indexes

app/controllers/OAIPMH.scala, test/integration/OaiPmhSpec.scala
wrong precision/format of timestamp, and incorrect character encoding for setSpec.
Alas, since setSpec tokens appear in OAI-PMH URLs, I had to mangle them completely to Base64 encoded values
Fixes: #348
=> Fixes 2 OAI-PMH validation errors:

.travis.yml, app/controllers/Search.scala, app/views/search/searchform.scala.html, app/workers/Indexer.scala, conf/application.conf, test/integration/SearchPagesSpec.scala
- Allows for authenticated, non-bonsai, elasticsearch. I've got some thread sleeps in there to prevent issues where we were sending data too fast for an upstream provider (at least on a free tier). A full reindex is now slower of course, but still completes in a reasonable amount of time. The delays should be unnoticeable to end users, but I still hate them. Ideally we'd read responses back and act accordingly (either sleeping or resending based on what the provider can seem to handle), but that level of refactor was way outside the scope of what I intended to do with this work.
closes #349 
- This also provides some initial integration tests with elasticsearch. Running tests locally now require an elasticsearch instance running. Travis spins one up for us. Much more can/should be tested, …
=> 349 generic elastic authentication

test/integration/SearchPagesSpec.scala
=> Adds additional search tests

app/services/sword.scala
I’m not sure why it takes so long for production dspace to spit out
this document, but it does.
Closes #367
=> Longer timeout before assuming service document load fails

app/workers/Conveyor.scala
=> Treats 202 status as success for Sword deposit

app/views/finder/create.scala.html, app/views/item/show.scala.html, public/stylesheets/main.css
This also removes abstract and changes the layout entirely.
closes #372 
(The modified form is a bug fix I noticed while working on this and is unrelated but seemed small enough to slide in with this work).
=> Adds DOI and pub date to Item show

app/models/Item.scala, conf/application.conf, test/unit/ItemSpec.scala
This allows setting METS_RESTRICT_MAXIMUM_AUTHORS to an integer. If
there are more authors than that number, none are supplied in the METS
to prevent triggering a bug in our local DSpace installation.
Fixes a bug where we included a title instead of the date.
Adds dc.agent as a mechanism for detecting the package came from
TopicHub. If a better field is identified, this could be changed and we
can work with Carl to update the crosswalk that relies on this value.
closes #371
closes #370
closes #375
=> METS author limits, date created, and TopicHub as agent
