- app/views/main.scala.html
- public/stylesheets/main.css
Adjusts top navigation padding and re-enables footer.
> Main template tweaks

- app/controllers/Application.scala
- app/workers/Harvester.scala
- conf/routes
> Adds Known Item Pull function

- app/views/item.scala.html
- app/views/item_browse.scala.html
- app/views/main.scala.html
- app/views/topic.scala.html
closes #4 
See individual commit messages for additional details.
> Math formulae display

- app/controllers/Application.scala
- app/services/email.scala
- app/views/layout/main.scala.html
- app/views/static/feedback.scala.html
- conf/application.conf
- conf/routes
> Adds email delivery service and User feedback form that use it

- app/views/item/show.scala.html
> Shows first item topic by default

- app/views/item/show.scala.html
closes #35 
This also allows the embedded math to display properly.
> Renders HTML in abstract

- app/controllers/Application.scala
- app/models/Interest.scala
- app/models/Scheme.scala
- app/models/Subscriber.scala
- app/services/jsonModel.scala
- app/views/static/workbench.scala.html
- app/views/subscriber/browse.scala.html
- app/views/subscriber/create.scala.html
- app/views/subscriber/edit.scala.html
- app/views/subscriber/index.scala.html
- app/views/subscriber/show.scala.html
- app/views/topic/show.scala.html
- app/views/utils/cmodel_create.scala.html
- conf/evolutions/default/2.sql
- conf/routes
Basic support for subscribers (add, edit, manage interests)
fixes #31
> Adds Subscriber and Interest

- app/models/Item.scala
- app/models/Topic.scala
- app/workers/Cataloger.scala
- app/workers/Indexer.scala
- conf/application.conf
> Adds indexing of items and topics

- app/workers/Indexer.scala
Work towards #51.
Additional calls to elastic search will require similar handling so I
thought it best to open a PR for discussion.
> Adds basic auth support for elasticsearch calls

- app/controllers/Search.scala
- app/models/HubUtils.scala
- app/views/search/searchform.scala.html
- app/workers/Indexer.scala
Remove html5 form validation from input
closes #63
Extract and use bonsai credentials for search and topic indexing
closes #62
closes #61
> Search and Indexing Bug Fixes

- app/controllers/Search.scala
closes #65 
(debug of json left in intentionally at this point as it's helpful to see in the logs for now what is happening in case further errors occur)
> invalid line break constructing a string

- app/controllers/Application.scala
- app/models/Hold.scala
- app/models/Subscriber.scala
- app/models/Subscription.scala
- app/models/Topic.scala
- app/models/Transfer.scala
- app/services/jsonModel.scala
- app/views/email/item_notify.scala.txt
- app/views/subscriber/edit.scala.html
- app/views/subscription/browse.scala.html
- app/views/topic/show.scala.html
- app/workers/Cataloger.scala
- app/workers/Conveyor.scala
- conf/evolutions/default/3.sql
- conf/routes
First cut subscriptions, transfers, and holds. UI only for subscriptions (via topic page, and link from 'interests' page
> 53 subscriptions and outcomes

- app/controllers/Application.scala
- app/models/Hold.scala
- app/models/Subscriber.scala
- app/views/hold/browse.scala.html
- app/views/item/show.scala.html
- app/views/layout/main.scala.html
- conf/routes
> Adds subscriber interface for managing holds (review)

- app/controllers/Application.scala
- app/workers/Indexer.scala
- conf/routes
> Activates Reindexing Feature

- app/models/Topic.scala
closes #19 
(well, sort of. I was unable to replicate #19 but this was close enough that I threw it on that ticket rather than opening a new one).
> Updates Topic browse to sort on Tag

- app/controllers/Application.scala
- app/workers/Packager.scala
> Adds SWORD package construction

- app/models/Item.scala
Updates mets generator to produce valid mets for dspace mets ingester
fixes #99
> Fix Mets generation

- app/models/Finder.scala
- app/services/jsonModel.scala
- app/workers/Cataloger.scala
> Allows multiple finders per format

- app/controllers/Application.scala
- app/controllers/ItemController.scala
- app/models/Hold.scala
- app/models/Subscriber.scala
- app/models/Subscription.scala
- app/models/Topic.scala
- app/workers/Conveyor.scala
- app/workers/Packager.scala
Subscription windows now pegged to Subscriber registration time, and SWORD deposit functions as the (sole) mode of
'delivery' Fixes #105
> Integrates SWORD deposit with subscription fulfillment

- .travis.yml
- README
- README.md
- app/models/Item.scala
- project/plugins.sbt
- test/unit/CollectionSpec.scala
- test/unit/ContentFormat.scala
- test/unit/ContentTypeSpec.scala
- test/unit/ItemSpec.scala
- test/unit/SchemeSpec.scala
- test/unit/TopicSpec.scala
This series of commits introduces Test Coverage reporting and begins the slog of work to actually write some meaningful tests.
This should bring us to about 24% test coverage. The models are about 60% tested.
It will start to get tricky doing tests of the workers and portions of the UI as so much relies on external HTTP calls. Capturing the results of HTTP calls once and replaying during testing is how I've handle this before and it looks like this project may be of use in that direction:
https://github.com/robfletcher/betamax
> 109 test coverage

- app/workers/Conveyor.scala
> Updates Channel transfer count when items delivered

- app/models/ContentProfile.scala
- test/unit/ContentProfileSpec.scala
> Prevents multiple scheme mappings in ContentProfile

- app/models/Topic.scala
- test/unit/TopicSpec.scala
> Checks for linked items in deleteUnlinkedBefore method

- app/controllers/Application.scala
- app/models/Subscriber.scala
- app/views/layout/main.scala.html
- app/views/subscriber/dashboard.scala.html
- conf/routes
- test/unit/SubscriberSpec.scala
closes #101
This will surely change over time, but is a first draft at exposing useful information for a Subscriber.
The tests cover the entire Subscriber model and not just the methods added for this work.
> 101 subscriber dashboard

- app/views/layout/main.scala.html
> Removes Review link on menu bar in favor of Dashboard

- app/controllers/Application.scala
- app/views/publisher/create.scala.html
- app/views/publisher/show.scala.html
- app/views/static/about.scala.html
- test/integration/PublisherPagesSpec.scala
- test/integration/StaticPagesSpec.scala
> Publisher and Static Pages Specs

- app/controllers/Application.scala
- app/models/Channel.scala
- app/models/Plan.scala
- app/models/Subscriber.scala
- app/services/jsonModel.scala
- app/views/layout/main.scala.html
- app/views/plan/create.scala.html
- app/views/plan/show.scala.html
- app/views/search/topic_results.scala.html
- app/views/static/workbench.scala.html
- app/views/subscriber/dashboard.scala.html
- app/views/subscriber/edit.scala.html
- app/views/topic/show.scala.html
- app/workers/Conveyor.scala
- conf/evolutions/default/8.sql
- conf/routes
- test/unit/ChannelSpec.scala
- test/unit/PlanSpec.scala
- test/unit/SubscriberSpec.scala
> Adds subscriber action plan to data model

- app/controllers/Application.scala
- app/views/content_type/create.scala.html
- app/views/content_type/show.scala.html
- test/integration/ContentTypePagesSpec.scala
> Content Type Page Specs

- app/controllers/Application.scala
- app/views/content_format/create.scala.html
- test/integration/ContentFormatPagesSpec.scala
> Content Format Page Specs

- .travis.yml
- app/controllers/Application.scala
- app/views/resource_map/create.scala.html
- app/views/resource_map/show.scala.html
- test/integration/ContentFormatPagesSpec.scala
- test/integration/ResourceMapPagesSpec.scala
> Resource Map Pages Specs

- app/controllers/ItemController.scala
- app/views/tags/pagination.scala.html
- test/integration/ItemPagesSpec.scala
Generating packages and delivering packages actions are currently
skipped.
We do test that non-signed in users or users without channels are
blocked from delivering. yay?
Part of #128
> Item pages specs

- app/controllers/Application.scala
- test/integration/TopicPagesSpec.scala
part of #128
Route for topicValidate is skipped. It was unclear what was intended
for it nor do we really have any validators at this time. When we start
creating validators, we should revisit this route.
> Topic Pages Spec

- app/controllers/Application.scala
- app/models/Channel.scala
- app/views/channel/create.scala.html
- app/views/plan/create.scala.html
- app/views/subscriber/create.scala.html
- conf/routes
- test/integration/ChannelPagesSpec.scala
- test/integration/PlanPagesSpec.scala
- test/integration/SubscriberPageSpec.scala
- test/unit/ChannelSpec.scala
- test/unit/TopicSpec.scala
part of #128
You may want to note the existence of the `getCurrentIdentity` private method in the application controller as it'll likely save you from reinventing that logic. It also make me cringe every time I look at it. I'll refactor eventually to get rid of the nested `if/else` blocks that the test env condition necessitates right now.
> Subscriber pages specs

- app/controllers/Application.scala
- app/views/subscription/browse.scala.html
- test/integration/SubscriptionPagesSpec.scala
> Subscription Browse Pages Specs

- app/controllers/Application.scala
- app/controllers/AuthenticationController.scala
- test/integration/IntegrationSpec.scala
- test/integration/SysAdminPagesSpec.scala
> Sysadmin and Analyst pages specs

- app/services/OAuth2.scala
- app/views/subscriber/create.scala.html
- app/views/subscriber/dashboard.scala.html
- test/integration/AuthenticationPagesSpec.scala
- test/integration/LoginRedirectSpec.scala
- test/unit/SubscriberSpec.scala
> Redirect user to useful page on login

- app/views/topic/show.scala.html
> Subscribing to a topic where a pick is active updates pick

- app/controllers/Application.scala
- app/models/Subscriber.scala
- app/services/OAuth2.scala
- app/services/email.scala
- app/views/email/subscriber_join_request.scala.txt
- app/views/email/subscriber_resolve.scala.txt
- app/views/layout/main.scala.html
- app/views/subscriber/create.scala.html
- app/views/subscriber/join.scala.html
- app/views/subscriber/request.scala.html
- app/views/subscriber/users.scala.html
- app/views/tags/flash.scala.html
- app/views/user/dashboard.scala.html
- conf/evolutions/default/10.sql
- conf/routes
- project/plugins.sbt
- test/integration/DashboardPagesSpec.scala
- test/integration/LoginRedirectSpec.scala
- test/integration/NavigationPagesSpec.scala
- test/integration/SubscriberPageSpec.scala
- test/integration/SubscriberUserPagesSpec.scala
- test/integration/UserDashboardPagesSpec.scala
- test/unit/ChannelSpec.scala
- test/unit/SubscriberSpec.scala
This PR encompasses many tickets, and to main features.
I've left it as two commits. Each commit comment has some reasonable detail.
1. Allow many Users for a Single Subscriber
2. All one User to have Multiple Subscribers
closes #192 
closes #176 
closes #177 
closes #191 
closes #46 
closes #182 
closes #179 
closes #178
> 192 multiple users per subscriber

- app/controllers/Application.scala
- app/models/Subscriber.scala
- test/integration/SubscriberUserPagesSpec.scala
closes #203
Also sets Session Subscriber on Subscriber Creation
closes #204
> Protects Session from Invalid Subscriber

- app/models/HubUtils.scala
- app/views/topic/browse.scala.html
> Supresses missing labels from topic browse lists

- app/services/jsonModel.scala
> Fixes silent JSON parse failure when loading models

- app/views/subscriber/dashboard.scala.html
> Adds link to subscriber users page from dashboard

- app/models/Item.scala
- app/views/subscriber/dashboard.scala.html
- test/unit/ItemSpec.scala
> Added item count to dashboard

- app/views/channel/create.scala.html
- app/views/collection/create.scala.html
- app/views/content_format/create.scala.html
- app/views/content_type/create.scala.html
- app/views/finder/create.scala.html
- app/views/harvest/create.scala.html
- app/views/helper/bootstrapHorizontal.scala.html
- app/views/plan/create.scala.html
- app/views/publisher/create.scala.html
- app/views/resource_map/create.scala.html
- app/views/scheme/create.scala.html
- app/views/static/feedback.scala.html
- app/views/static/sandbox.scala.html
- app/views/subscriber/create.scala.html
- app/views/validator/create.scala.html
- test/integration/ChannelPagesSpec.scala
- test/integration/ContentFormatPagesSpec.scala
- test/integration/ContentTypePagesSpec.scala
- test/integration/FinderPagesSpec.scala
- test/integration/ResourceMapPagesSpec.scala
- test/integration/SchemePagesSpec.scala
This attempts to present a cleaner UI by both using bootstrap form styles and moving
as much help as possible inline to the appropriate element.
closes #23
> Improves Aesthetics and Usefulness of most forms

- project/plugins.sbt
> update to play 2.4.2 bug fix release

- app/controllers/ItemController.scala
> Redirect back to Item page with a flash

- app/models/HubUtils.scala
- app/models/Scheme.scala
- app/views/scheme/show.scala.html
- test/unit/SchemeSpec.scala
> Adds visualization of item coverage by scheme

- app/controllers/Application.scala
- app/views/item/show.scala.html
- test/integration/ItemPagesSpec.scala
Also does some minor aesthetic cleanup and adds a flash message when
delivering or ignoring a held item.
closes #282
> Only display Deliver OR Deposit links

- app/views/subscriber/dashboard.scala.html
> Handle aborted drags

- app/workers/Cataloger.scala
> Match new topics to subscriber interests

- app/controllers/Application.scala
- conf/routes
This uses the same key as harvests to allow for reindexing.
closes #238
> Allow reindex jobs to be triggered by cron

- app/views/subscriber/index.scala.html
- test/integration/SubscriberPageSpec.scala
> Adjust display for Subscriber Index

- app/controllers/Application.scala
- app/views/interest/browse.scala.html
- app/views/scheme/show.scala.html
- conf/routes
- test/integration/SubscriberInterestPagesSpec.scala
Also adds protection for Subscriber Interest routes (and tests for
same).
Closes #187
Closes #297
> Allow deletion of template Interests

- app/workers/Conveyor.scala
Specifically, define the notion of a 'default plan' (currently, the default plan is the oldest created plan)
whose channel is used when no other channel (based on plan coverage) is indicated.
Closes #303
> Add channel selection rules for delivery actions

- app/controllers/Application.scala
- test/integration/ChannelPagesSpec.scala
> Adds default plans and channels for new subscribers

- app/views/hold/browse.scala.html
- public/stylesheets/main.css
> Add deliver, discard option to hold browse view

- conf/application.conf
> Updates default admin email and allows ENV override

- app/controllers/OAIPMH.scala
- app/models/Item.scala
- app/models/Topic.scala
- app/views/static/about.scala.html
- conf/routes
- test/unit/ItemSpec.scala
- test/unit/TopicSpec.scala
with topics as OAI sets
Closes #305
> Adds support for OAI protocol for metadata harvesting (OAI-PMH)

- app/models/Subscriber.scala
- app/views/subscriber/dashboard.scala.html
- test/unit/SubscriberSpec.scala
> Provides links to Interests by Scheme on Subscriber Dashboard

- app/models/HubUtils.scala
- app/views/subscriber/dashboard.scala.html
> Formats date of last Harvest for display

- test/integration/ItemPagesSpec.scala
- test/integration/OaiPmhSpec.scala
This covers some additional paths in the Item Pages as well as does some initial fairly hacky OAI-PMH testing.
> Increase test coverage

- app/controllers/Application.scala
- app/services/sword.scala
- app/views/channel/show.scala.html
- conf/routes
> Adds SWORD endpoint checking on destination page

- app/services/OAuth2.scala
> Updates some inappropriate error messages

- app/controllers/Search.scala
- app/views/layout/main.scala.html
- app/views/static/about.scala.html
- conf/routes
with Atom formatting.
Closes #355
> Add OpenSearch support for item searching

- build.sbt
- project/plugins.sbt
> Updates play, anorm, bootstrap and pg to latest
